# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
search                   : true # enable site search
title                    : Jared Kzy
title_separator          : "-"
url                      : https://j-red.github.io
baseurl                  : "" # e.g., "/blog" if hosted in a subdirectory
words_per_minute         : 160

author:
  name: j-red
  email: jared@cs.uoregon.edu
  bio: "PhD Student, Technical Artist, and Internet Data Scientist currently located in Oregon."
  location: "Eugene, Oregon"
  avatar: "profile.png"
  # employer: 
  github: "j-red"
  orcid: "https://orcid.org/0000-0002-6658-8527"
  linkedin: "knofczynski"
  twitter: "okcomputerrrrrr"
  # soundcloud: 
  # stackoverflow:

twitter: "okcomputerrrrrr"

description: > # this means to ignore newlines until "show_excerpts:"
  PhD student, Technical Artist, and Internet Data Scientist currently located in Oregon.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: okcomputerrrrrr
    github_username:  j-red
    github:  j-red
    orcid: 0000-0002-6658-8527
    linkedin: 
    soundcloud: 
    stackoverflow: 
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: knofczynski
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- about.md
- portfolio.md
- publications.md
- cv.md
- blog.md

# Build settings
theme: minima
minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-redirect-from
  # - jekyll-email-protect

author:
  # name: John Smith
  email: "jared@cs.uoregon.edu"

whitelist:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-redirect-from
  # - jekyll-email-protect