# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
search                   : true # enable site search
title                    : Jared Kzy
title_separator          : "-"
url                      : https://j-red.github.io
baseurl                  : "" # e.g., "/blog" if hosted in a subdirectory
words_per_minute         : 160

author:
  name: j-red
  email: jared@cs.uoregon.edu
  bio: "Freelance Technical Artist and Ph.D. student from the Pacific Northwest."
  location: "Pacific Northwest"
  avatar: "profile.png"
  employer: 

twitter: "okcomputerrrrrr"

description: > # this means to ignore newlines until "show_excerpts:"
  Technical Artist & Ph.D. student from the Pacific Northwest.

show_excerpts: true # set to true to show excerpts on the homepage

socials:
  twitter: okcomputerrrrrr
  github_username:  j-red
  github:  j-red
  #orcid: 0000-0002-6658-8527
  # linkedin: 
  soundcloud: 
  stackoverflow: 
  # devto: jekyll
  # dribbble: jekyll
  # facebook: jekyll
  # flickr:   jekyll
  # instagram: jekyll
  # pinterest: jekyll
  # youtube: jekyll
  # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
  # youtube_channel_name: 
  # telegram: jekyll
  # googleplus: +jekyll
  # microdotblog: jekyll
  # keybase: jekyll

  # Mastodon instances
  # mastodon:
  # - username: jekyll
  #   instance: example.com
  # - username: jekyll2
  #   instance: example.com

  # GitLab instances
  # gitlab:
  # - username: jekyll
  #   instance: example.com
  # - username: jekyll2
  #   instance: example.com

# Minima date format
date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- about.md
- portfolio.html
- publications.md
- resume.html
- cv.md
- blog.md

# Build settings
theme: minima
minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-redirect-from
  # - jekyll-email-protect

author:
  # name: John Smith
  email: "jared@cs.uoregon.edu"

whitelist:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-redirect-from
  # - jekyll-email-protect